version: '3.4'

services:
  users:
    container_name: users
    build: 
      context: ./services/users
      dockerfile: Dockerfile-prod
    volumes:
      -'/services/users:/usr/src/app'
    ports:
      -5001:5000
    environment:
      - FLASK_DEBUG = 1
      - APP_SETTINGS = project.config.ProductionConfig
      - DATABASE_URL = postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_URL = postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db  

  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: dockerfile
    ports:
      -5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
    expose:
      - '5000'