FROM python:3.10.9

# install environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
    netcat \
    && apt-get install -p clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requireements
COPY ./requirements.txt /usr/src/app/requireements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# add server
CMD ["./entrypoint.sh"] 